### ISSUE TITLE
Release Drafter is missing the PR number w.r.t each PR.

### ISSUE THREAD

**Issue by srivarra** [angelolab/.github#7]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
It seems like the Release Drafter broke at some point. The PR numbers do not exist. For an example, the [release draft for ark](https://github.com/angelolab/ark-analysis/releases/tag/untagged-0fceff20e8ee7b6aa74c). This is happening to each repo. Looks like others are having the same [issue](https://github.com/release-drafter/release-drafter/issues/1223)

**Expected behavior**
The release draft should contain the PR numbers like in [ark-analysis v0.4.2](https://github.com/angelolab/ark-analysis/releases/tag/v0.4.1).

**To Reproduce**
N/A.

**Comment by ngreenwald** [comment]
While you're at it, can you also update it to include names of PRs only, not the full text of the PR description?
